# Generated by Django 3.1.4 on 2021-01-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submit',
            old_name='divsion',
            new_name='division',
        ),
    ]
